[server]
enableXsrfProtection = true  # Protección XSRF para peticiones de usuario

[client]
hideMenuItems = true         # Oculta el menú de ajustes

# Establece el límite máximo de tamaño de archivo en MB
[server]
maxUploadSize = 20

